package com.model;
 
/**
 * TXinxi generated by MyEclipse Persistence Tools
 */

public class TXinxi implements java.io.Serializable
{

	private Integer id;
	private String neirong;
	private String leixing;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getLeixing()
	{
		return leixing;
	}
	public void setLeixing(String leixing)
	{
		this.leixing = leixing;
	}
	public String getNeirong()
	{
		return neirong;
	}
	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}

}